[package]
name = "rdtach"
version = "0.0.1"
authors = ["yazgoo"]
description = "Dtach in rust"
documentation = "https://docs.rs/rdtach"
homepage = "https://github.com/yazgoo/rdtach"
repository = "https://github.com/yazgoo/rdtach"
readme  = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"
edition = "2018"

[dependencies]
nix = "0.25"
anyhow = "1.0"
termion = "1"
pty = "0.2"
bincode = "1.0"
serde = { version = "1.0", features = ["derive"] }
signal-hook = "0.3" 
daemonize = "0.4"
